schema: ./path/to/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: import.meta.env.VITE_GRAPHQL_ENDPOINT
      headers:
        user-agent: JS GraphQL
      introspect: false
